# Generated by Django 2.0.2 on 2018-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180422_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='f1score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='falsepositiverate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='recall',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='truepositiverate',
            field=models.FloatField(default=0),
        ),
    ]
